spring.application.name=EurekaServer
server.port=8761


#prevents server to be act as eureka client and fetch other registry
eureka.client.fetch-registry=false
#prevents server to be registered as clients to other eureka servers
eureka.client.register-with-eureka=false